name: rust-build release

on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            output: mcwpack-windows
            archive: zip
          - target: x86_64-unknown-linux-musl
            output: mcwpack-linux
            archive: tar.gz
          - target: x86_64-apple-darwin
            output: mcwpack-macos
            archive: zip
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
          ARCHIVE_NAME: ${{ matrix.output }}
          EXTRA_FILES: "README.md LICENSE"
